services:
  - type: web
    name: drukarena
    runtime: go
    plan: free
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app
    startCommand: ./app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: drukarena-db
          property: connectionString
      - key: UPLOAD_DIR
        value: /tmp/drukarena/uploads

databases:
  - name: drukarena-db
    plan: free
